#########################################################################
# File Name: train.sh
# Author: ma6174
# mail: ma6174@163.com
# Created Time: Tue Apr 18 20:21:18 2017
#########################################################################
#!/bin/bash

#id=0 baseline
#CUDA_VISIBLE_DEVICES=7 th train.lua -input_h5 coco/cocotalk_kar.h5 -input_json coco/cocotalk_kar.json -cnn_proto model/VGG_ILSVRC_19_layers_deploy.prototxt -cnn_model ../multi-label/VGG_ILSVRC_19_layers.caffemodel -checkpoint_path ./snapshot  -language_eval 1 -id 0 -finetune_cnn_after 0 -start_from snapshot/model_id0.t7 -gpuid 0 2>&1 | tee log_training_id0_stage2.txt


#id=1 vgg finetuned by t100 lmdb1
#CUDA_VISIBLE_DEVICES=6 th train.lua -input_h5 coco/cocotalk_kar.h5 -input_json coco/cocotalk_kar.json -cnn_proto model/VGG_ILSVRC_19_layers_deploy.prototxt -cnn_model ../multi-label/model_vgg19/lmdb1/vgg19_snapshot_iter_25000.caffemodel -checkpoint_path ./snapshot  -language_eval 1 -id 1_stage2 -finetune_cnn_after 0 -start_from snapshot/model_id1.t7 -gpuid 0 2>&1 | tee log_training_id1_stage2.txt

#for test
#for beam_size in 1 2 3 4 5 6
#do
#  CUDA_VISIBLE_DEVICES=3 th train.lua -input_h5 coco/cocotalk_kar.h5 -input_h5_topics coco/cocotalk_topics-t200-lmdb1bak_kar.h5 -input_json coco/cocotalk_kar.json -cnn_proto model/VGG_ILSVRC_19_layers_deploy_emb.prototxt -cnn_model model/VGG_ILSVRC_19_layers_deploy_emb_0.2.caffemodel -fcn_proto model/topic_emb.prototxt -fcn_model model/topic_emb_0.2.caffemodel -checkpoint_path ./snapshot -language_eval 1 -topic_num 200 -start_from snapshot/model_idT2_1-0.2_2_stage3_cnn-only_lr1e-5_cnn-fcn-w-lr4e-3_2.t7 -beam_size $beam_size -id x2 -gpuid 0 2>&1 | tee log_training_idx-T2_1-0.2_2_stage3_cnn-only_lr1e-5_cnn-fcn-w-lr4e-3_2_beam${beam_size}.txt
#done
#CUDA_VISIBLE_DEVICES=5 th train.lua -net_type 1 -input_h5 coco/cocotalk_kar.h5 -input_h5_topics coco/cocotalk_topics-t200-lmdb1bak_kar.h5 -input_json coco/cocotalk_kar.json -cnn_proto model/VGG_ILSVRC_19_layers_deploy_emb.prototxt -cnn_model model/VGG_ILSVRC_19_layers_deploy_emb_0.2.caffemodel -fcn_proto model/topic_emb.prototxt -fcn_model model/topic_emb_0.2.caffemodel -checkpoint_path ./snapshot -language_eval 1 -topic_num 200 -start_from snapshot/model_idT2_1-0.2_2_stage3_cnn-only_lr1e-5_2.t7 -beam_size 1 -id xcaptionsample_beam1 -gpuid 0 2>&1 | tee log_training_idxcaptionsample_beam1.txt


#id=t1 vgg finetuned by t100 lmdb1
#CUDA_VISIBLE_DEVICES=5 th train.lua -input_h5 coco/cocotalk_kar.h5 -input_h5_topics coco/cocotalk_topics_kar.h5 -input_json coco/cocotalk_kar.json -cnn_proto model/VGG_ILSVRC_19_layers_deploy_emb.prototxt -cnn_model model/VGG_ILSVRC_19_layers_deploy_emb_0.2.caffemodel -fcn_proto model/topic_emb.prototxt -fcn_model model/topic_emb_0.2.caffemodel -checkpoint_path ./snapshot  -language_eval 1 -id t1 -gpuid 0 2>&1 | tee log_training_idt1.txt
#CUDA_VISIBLE_DEVICES=4 th train.lua -input_h5 coco/cocotalk_kar.h5 -input_h5_topics coco/cocotalk_topics_kar.h5 -input_json coco/cocotalk_kar.json -cnn_proto model/VGG_ILSVRC_19_layers_deploy_emb.prototxt -cnn_model model/VGG_ILSVRC_19_layers_deploy_emb_0.2.caffemodel -fcn_proto model/topic_emb.prototxt -fcn_model model/topic_emb_0.2.caffemodel -topic_num 100 -finetune_cnn_after 0 -cnn_learning_rate 1e-5 -start_from snapshot/model_idt1_1-0.2.t7 -save_checkpoint_every 2500 -checkpoint_path ./snapshot  -language_eval 1 -id t1_1-0.2_stage2_cnn-only_lr1e-5 -gpuid 0 2>&1 | tee log_t1_1-0.2_stage2_cnn-only_lr1e-5.txt

#t1:0.2, t2:0.1, t3:0.5, t4:1pair_0.2, t5:expand-new_0.2, t6:0.3, t7:topic200-0.2, T1:0.2-lmdb2-topic100
#T2:0.2-lmdb1bak-topic200
#CUDA_VISIBLE_DEVICES=2 th train.lua -input_h5 coco/cocotalk_kar.h5 -input_h5_topics coco/cocotalk_topics-t200-lmdb1bak_kar.h5 -input_json coco/cocotalk_kar.json -cnn_proto model/VGG_ILSVRC_19_layers_deploy_emb.prototxt -cnn_model model/VGG_ILSVRC_19_layers_deploy_emb_t200_0.2.caffemodel -fcn_proto model/topic_emb_t200.prototxt -fcn_model model/topic_emb_t200_0.2.caffemodel -topic_num 200 -max_iters 100000 -save_checkpoint_every 7500 -checkpoint_path ./snapshot  -language_eval 1 -id T2_1-0.2_2 -gpuid 0 2>&1 | tee log_T2_1-0.2_2.txt
#CUDA_VISIBLE_DEVICES=2 th train.lua -net_type 1 -input_h5 coco/cocotalk_kar.h5 -input_h5_topics coco/cocotalk_topics-t200-lmdb1bak_kar.h5 -input_json coco/cocotalk_kar.json -cnn_proto model/VGG_ILSVRC_19_layers_deploy_emb.prototxt -cnn_model model/VGG_ILSVRC_19_layers_deploy_emb_t200_0.2.caffemodel -fcn_proto model/topic_emb_t200.prototxt -fcn_model model/topic_emb_t200_0.2.caffemodel -topic_num 200 -save_checkpoint_every 2500 -finetune_cnn_after 0 -cnn_learning_rate 1e-5 -start_from snapshot/model_idT2_1-0.2_cnn-only_lr1e-5.t7 -learning_rate_decay_start 0 -learning_rate_decay_every 50000 -checkpoint_path ./snapshot  -language_eval 1 -id T2_1-0.2_stage3_cnn-only_lr1e-5 -gpuid 0 2>&1 | tee log_T2_1-0.2_stage3_cnn-only_lr1e-5.txt
#CUDA_VISIBLE_DEVICES=3 th train.lua -net_type 1 -input_h5 coco/cocotalk_kar.h5 -input_h5_topics coco/cocotalk_topics-t200-lmdb1bak_kar.h5 -input_json coco/cocotalk_kar.json -cnn_proto model/VGG_ILSVRC_19_layers_deploy_emb.prototxt -cnn_model model/VGG_ILSVRC_19_layers_deploy_emb_t200_0.2.caffemodel -fcn_proto model/topic_emb_t200.prototxt -fcn_model model/topic_emb_t200_0.2.caffemodel -topic_num 200 -learning_rate 5e-5 -finetune_cnn_after 0 -cnn_learning_rate 1e-6 -finetune_cnn_fcn_w_after 0 -cnn_fcn_w_learning_rate 4e-4 -start_from snapshot/model_idT2_1-0.2_2_stage3_cnn-only_lr1e-5_2.t7 -checkpoint_path ./snapshot  -language_eval 1 -id T2_1-0.2_2_stage3_rnn-5e-5_cnn-only_lr1e-5_2_stage4_cnn-lr1e-6_cnn-fcn-w-lr4e-4 -gpuid 0 2>&1 | tee log_T2_1-0.2_2_stage3_rnn-5e-5_cnn-only_lr1e-5_2_stage4_cnn-fcn-w-lr4e-4.txt


#R1 resnet-t200-lmdb1bak(false GBR) R2-(true RGB) R3-(true bn-layer mean,var)
#CUDA_VISIBLE_DEVICES=4 th train.lua -input_h5 coco/cocotalk_kar.h5 -input_h5_topics coco/cocotalk_topics-t200-lmdb1bak-resnet_kar.h5 -input_json coco/cocotalk_kar.json -cnn_proto model/model_resnet101_deploy_emb.prototxt -cnn_model model/model_resnet101_deploy_emb2.caffemodel -val_images_use 4998 -batch_size 12 -topic_num 200 -save_checkpoint_every 7500 -checkpoint_path ./snapshot  -language_eval 1 -id R3_stage1_tunebn_bs12 -gpuid 0 -max_iters 150000 2>&1 | tee log_R3_stage1_tunebn_bs12.txt
#CUDA_VISIBLE_DEVICES=0 th train.lua -input_h5 coco/cocotalk_kar.h5 -input_h5_topics coco/cocotalk_topics-t200-lmdb1bak-resnet_kar.h5 -input_json coco/cocotalk_kar.json -cnn_proto model/model_resnet101_deploy_emb.prototxt -cnn_model model/model_resnet101_deploy_emb2.caffemodel -val_images_use 5000 -start_from snapshot/model_idR2_stage3-fixbn_fixbn_bs12-1e-5_lrdec-50000.t7 -max_iters 100 -batch_size 16 -topic_num 200 -save_checkpoint_every 7500 -checkpoint_path ./snapshot  -language_eval 1 -id tmp2 -gpuid 0 2>&1 | tee log_tmp2.txt
#CUDA_VISIBLE_DEVICES=6 th train.lua -eval_test2014 1 -input_h5 coco/cocotalk_kar.h5 -input_h5_topics coco/cocotalk_topics-t200-lmdb1bak-resnet_kar.h5 -input_json coco/cocotalk_kar.json -input_h52 coco/cocotalk_test2014.h5 -input_h5_topics2 coco/cocotalk_topics-t200-lmdb1bak-resnet_test2014.h5 -input_json2 coco/cocotalk_test2014.json  -cnn_proto model/model_resnet101_deploy_emb.prototxt -cnn_model model/model_resnet101_deploy_emb2.caffemodel -val_images_use 40775 -start_from snapshot/model_idR2_stage3-fixbn_fixbn_bs12-1e-5_lrdec-50000.t7 -max_iters 100 -batch_size 10 -topic_num 200 -save_checkpoint_every 7500 -checkpoint_path ./snapshot  -language_eval 1 -id test2014 -gpuid 0 2>&1 | tee log_test2014.txt
#CUDA_VISIBLE_DEVICES=1 th train.lua -eval_test2014 1 -input_h5 coco/cocotalk_kar.h5 -input_h5_topics coco/cocotalk_topics-t200-lmdb1bak-resnet_kar.h5 -input_json coco/cocotalk_kar.json -input_h52 coco/cocotalk_val2014.h5 -input_h5_topics2 coco/cocotalk_topics-t200-lmdb1bak-resnet_val2014.h5 -input_json2 coco/cocotalk_val2014.json  -cnn_proto model/model_resnet101_deploy_emb.prototxt -cnn_model model/model_resnet101_deploy_emb2.caffemodel -val_images_use 40504 -start_from snapshot/model_idR2_stage3-fixbn_fixbn_bs12-1e-5_lrdec-50000.t7 -max_iters 100 -batch_size 16 -topic_num 200 -save_checkpoint_every 7500 -checkpoint_path ./snapshot  -language_eval 1 -id val2014 -gpuid 0 2>&1 | tee log_val2014.txt

#CUDA_VISIBLE_DEVICES=3 th train.lua -input_h5 coco/cocotalk_kar.h5 -input_h5_topics coco/cocotalk_topics-t200-lmdb1bak-resnet_kar.h5 -input_json coco/cocotalk_kar.json -cnn_proto model/model_resnet101_deploy_emb.prototxt -cnn_model model/model_resnet101_deploy_emb2.caffemodel -finetune_cnn_after 0 -start_from snapshot/model_idR3_stage1_fixbn_bs12_iter397500.t7 -cnn_learning_rate 1e-5 -batch_size 12 -val_images_use 4998 -topic_num 200 -save_checkpoint_every 2500 -checkpoint_path ./snapshot  -language_eval 1 -id R3_stage2-fixbn-iter397500_fixbn_bs12-1e-5 -gpuid 0 2>&1 | tee log_R3_stage2-fixbn-iter397500_fixbn_bs12-1e-5.txt

#CUDA_VISIBLE_DEVICES=4 th train.lua -input_h5 coco/cocotalk_kar.h5 -input_h5_topics coco/cocotalk_topics-t200-lmdb1bak-resnet_kar.h5 -input_json coco/cocotalk_kar.json -cnn_proto model/model_resnet101_deploy_emb.prototxt -cnn_model model/model_resnet101_deploy_emb2.caffemodel -finetune_cnn_after 0 -start_from snapshot/model_idR3_stage2-fixbn-iter337500_fixbn_bs12-1e-5.t7 -cnn_learning_rate 1e-5 -learning_rate_decay_start 0 -learning_rate_decay_every 50000 -batch_size 12 -val_images_use 4998 -topic_num 200 -save_checkpoint_every 2500 -checkpoint_path ./snapshot  -language_eval 1 -id R3_stage2-fixbn-iter337500_fixbn_bs12-1e-5_lrdec-50000 -gpuid 0 2>&1 | tee log_R3_stage2-fixbn-iter337500_fixbn_bs12-1e-5_lrdec-50000.txt

#CUDA_VISIBLE_DEVICES=1 th train.lua -input_h5 coco/cocotalk_kar.h5 -input_h5_topics coco/cocotalk_topics-t200-lmdb1bak-resnet_kar.h5 -input_json coco/cocotalk_kar.json -cnn_proto model/model_resnet101_deploy_emb.prototxt -cnn_model model/model_resnet101_deploy_emb2.caffemodel -finetune_cnn_after 0 -start_from snapshot/model_idR2_stage1_fixbn_bs12.t7 -batch_size 12 -val_images_use 1200 -topic_num 200 -save_checkpoint_every 100 -max_iters 120 -checkpoint_path ./snapshot  -language_eval 1 -id tmp2 -gpuid 0 2>&1 | tee log_tmp2.txt
#CUDA_VISIBLE_DEVICES=1 th train.lua -input_h5 coco/cocotalk_kar.h5 -input_h5_topics coco/cocotalk_topics-t200-lmdb1bak-resnet_kar.h5 -input_json coco/cocotalk_kar.json -cnn_proto model/model_resnet101_deploy_emb.prototxt -cnn_model model/model_resnet101_deploy_emb2.caffemodel -finetune_cnn_after 0 -start_from snapshot/model_idtmp2.t7 -batch_size 12 -val_images_use 1200 -topic_num 200 -save_checkpoint_every 100 -max_iters 120 -checkpoint_path ./snapshot  -language_eval 1 -id tmp3 -gpuid 0 2>&1 | tee log_tmp3.txt





#CUDA_VISIBLE_DEVICES=3 th train.lua -input_h5 coco/cocotalk_kar.h5 -input_h5_topics coco/cocotalk_topics-t200-lmdb1bak-resnet_kar.h5 -input_json coco/cocotalk_kar.json -cnn_proto model/model_resnet101_deploy_emb.prototxt -cnn_model model/model_resnet101_deploy_emb2.caffemodel -start_from snapshot/model_idR2_stage2-fixbn_fixbn_bs12-1e-5.t7 -batch_size 16 -val_images_use 5000 -topic_num 200 -save_checkpoint_every 2500 -checkpoint_path ./snapshot  -language_eval 1 -id R2_eval -gpuid 0 2>&1 | tee log_R2_eval.txt


